const connectorODS = {
    "End Poverty": [["Poverty", "Inequality", "Inclusion", "Well-being"], ["Unemployment", "Wealth", "Opportunities", "Education"],  ["Crisis", "Extreme poverty", "Vulnerability", "Intervention"]],
    "Zero Hunger": [["Nutrition", "Sustainability", "Agriculture", "Food"], ["Malnutrition", "Production", "Insecurity", "Sustainability"], ["Sustainable agriculture", "Food security", "Access to food", "Local production"]],
    "Good Health and Well-being": [["Healthcare", "Diseases", "Mental health", "Well-being"], ["Prevention", "Public health", "Immunization", "Access"], ["Health promotion", "Medicine", "Chronic diseases", "Disease prevention"]],
    "Quality Education": [["Access", "Inclusion", "Learning", "Opportunities"], ["Quality", "Equity", "Instruction", "Development"], ["Inclusive education", "Educational quality", "Vocational training", "Skills development"]],
    "Gender Equality": [["Empowerment", "Rights", "Equity", "Violence"], ["Diversity", "Autonomy", "Gender violence", "Rights"], ["Workplace equality", "Gender education", "Economic empowerment", "Reproductive health"]],
    "Clean Water and Sanitation": [["Access", "Quality", "Sustainability", "Hygiene"], ["Pollution", "Safe access", "Treatment", "Sanitation"], ["Drinking water", "Water resource management", "Water conservation", "Basic sanitation"]],
    "Decent Work and Economic Growth": [["Employment", "Growth", "Sustainability", "Opportunities"], ["Dignified work", "Working conditions", "Labor rights", "Inclusion"], ["Fair wages", "Equity", "Access", "Empowerment"]],
    "Industry, Innovation, and Infrastructure": [["Technology", "Development", "Infrastructure", "Innovation"], ["Mobility", "Networks", "Connectivity", "Sustainability"], ["Technological innovation", "Green growth", "Industrial development", "Economic sustainability"]],
    "Reduced Inequalities": [["Inclusion", "Equity", "Opportunities", "Diversity"], ["Inequality", "Opportunities", "Social inclusion", "Cultural diversity"], ["Poverty reduction", "Social equity", "Rural development", "Inclusive policies"]],
    "Sustainable Cities and Communities": [["Urbanization", "Sustainability", "Infrastructure", "Inclusion"], ["Quality of life", "Basic services", "Urban development", "Access"], ["Security", "Resilience", "Climate change", "Natural disasters"]],
    "Responsible Consumption and Production": [["Sustainability", "Waste", "Efficiency", "Resources"], ["Circular economy", "Recycling", "Responsible production", "Responsible consumption"], ["Supply chain", "Ecological footprint", "Sustainability", "Circular economy"]],
    "Climate Action": [["Climate change", "Mitigation", "Adaptation", "Sustainability"], ["Greenhouse effect", "Natural resources", "Adaptation", "Prevention"], ["Environmental sustainability", "Energy efficiency", "Sustainable production", "Responsible development"]],
    "Life Below Water": [["Conservation", "Marine resources", "Biodiversity", "Sustainability"], ["Marine ecosystems", "Pollution", "Sustainability", "Resources"], ["Biodiversity", "Marine conservation", "Environmental impact", "Coastal development"]],
    "Life on Land": [["Conservation", "Biodiversity", "Ecosystems", "Sustainability"], ["Forests", "Conservation", "Species", "Sustainable development"], ["Ecosystem restoration", "Species conservation", "Forest resources", "Sustainable management"]],
    "Peace, Justice and Strong Institutions": [["Human rights", "Justice", "Peace", "Governance"], ["Participation", "Transparency", "Trust", "Social justice"], ["Collaboration", "Strategic alliances", "Local development", "Cooperation networks"]],
    "Partnerships for the Goals": [["Cooperation", "Partnerships", "Sustainability", "Development"], ["Sustainable development", "International cooperation", "Public policies", "Partnerships"], ["Regional development", "Citizen participation", "Inclusive governance", "Civil society"]],
}
export default connectorODS ;