const connectorODS = {
    "Fin de la pobreza": [["Pobreza", "Desigualdad", "Inclusión", "Bienestar"], ["Desempleo", "Riqueza", "Oportunidades", "Educación"],  ["Crisis", "Pobreza extrema", "Vulnerabilidad", "Intervención"]],
    "Hambre cero":[["Nutrición","Sostenibilidad", "Agricultura", "Alimentación"], ["Desnutrición", "Producción", "Inseguridad", "Sustentabilidad"], ["Agricultura sostenible", "Seguridad alimentaria", "Acceso a alimentos", "Producción local"]],
    "Salud y bienestar": [["Atención médica", "Enfermedades", "Salud mental", "Bienestar"],  ["Prevención", "Salud pública", "Inmunización", "Acceso"], ["Promoción de la salud", "Medicina", "Enfermedades crónicas", "Prevención de enfermedades"]],
    "Educación de calidad":[["Acceso" , "Inclusión" , "Aprendizaje" , "Oportunidades"],["Calidad", "Equidad", "Instrucción", "Desarrollo"],  ["Educación inclusiva", "Calidad educativa", "Formación profesional", "Desarrollo de habilidades"]],
    "Igualdad de género": [["Empoderamiento" , "Derechos" , "Equidad" , "Violencia"],  ["Diversidad", "Autonomía", "Violencia de género", "Derechos"],["Igualdad en el trabajo", "Educación de género", "Empoderamiento económico", "Salud reproductiva"]],
    "Agua limpia y saneamiento": [["Acceso", "Calidad", "Sostenibilidad", "Higiene"], ["Contaminación", "Acceso seguro", "Tratamiento", "Saneamiento"],["Agua potable", "Gestión de recursos hídricos", "Conservación de agua", "Saneamiento básico"]],
    "Trabajo decente y crecimiento económico": [["Empleo", "Crecimiento", "Sostenibilidad", "Oportunidades"], ["Trabajo digno", "Condiciones laborales", "Derechos laborales", "Inclusión"],["Salario justo", "Equidad", "Acceso", "Empoderamiento"]  ],
    "Industria, innovación e infraestructura": [["Tecnología", "Desarrollo", "Infraestructura", "Innovación"], ["Movilidad", "Redes", "Conectividad", "Sostenibilidad"], ["Innovación tecnológica", "Crecimiento verde", "Desarrollo industrial", "Sostenibilidad económica"]],
    "Reducción de las desigualdades": [["Inclusión", "Equidad", "Oportunidades", "Diversidad"], ["Desigualdad", "Oportunidades", "Inclusion social", "Diversidad cultural"], ["Reducción de la pobreza", "Equidad social", "Desarrollo rural", "Políticas inclusivas"] ],
    "Ciudades y comunidades sostenibles": [["Urbanización", "Sostenibilidad", "Infraestructura", "Inclusión"], ["Calidad de vida", "Servicios básicos", "Desarrollo urbano", "Acceso"],["Seguridad", "Resiliencia", "Cambio climático", "Desastres naturales"] ],
    "Producción y consumo responsables": [["Sostenibilidad", "Residuos", "Eficiencia", "Recursos"], ["Economía circular", "Reciclaje", "Producción responsable", "Consumo responsable"] , ["Cadena de suministro", "Huella ecológica", "Sustentabilidad", "Economía circular"]],
    "Acción por el clima": [["Cambio climático", "Mitigación", "Adaptación", "Sostenibilidad"], ["Efecto invernadero", "Recursos naturales", "Adaptación", "Prevención"], ["Sostenibilidad ambiental", "Eficiencia energética", "Producción sostenible", "Desarrollo responsable"] ],
    "Vida submarina": [["Conservación", "Recursos marinos", "Biodiversidad", "Sostenibilidad"], ["Ecosistemas marinos", "Contaminación", "Sostenibilidad", "Recursos"],["Biodiversidad", "Conservación marina", "Impacto ambiental", "Desarrollo costero"] ],
    "Vida de ecosistemas terrestres": [["Conservación", "Biodiversidad", "Ecosistemas", "Sostenibilidad"], ["Bosques", "Conservación", "Especies", "Desarrollo sostenible"],["Restauración de ecosistemas", "Conservación de especies", "Recursos forestales", "Gestión sostenible"]],
    "Paz, justicia e instituciones sólidas": [["Derechos humanos", "Justicia", "Paz", "Gobernanza"], ["Participación", "Transparencia", "Confianza", "Justicia social"], ["Colaboración", "Alianzas estratégicas", "Desarrollo local", "Redes de cooperación"]],
    "Alianzas para lograr los objetivos": [["Cooperación", "Alianzas", "Sostenibilidad", "Desarrollo"], ["Desarrollo sostenible", "Cooperación internacional", "Políticas públicas", "Asociaciones"], ["Desarrollo regional", "Participación ciudadana", "Gobernanza inclusiva", "Sociedad civil"]],
}

export { connectorODS };