import { extendTheme } from '@chakra-ui/react'

// example theme
const theme = extendTheme({
  colors: {
    "No Poverty": "#E5243B",
    "Zero Hunger": "#DDA63A",
    "Good Health and Well-being": "#4C9F38",
    "Quality Education": "#C5192D",
    "Gender Equality": "#FF3A21",
    "Clean Water and Sanitation": "#26BDE2",
    "Affordable and Clean Energy": "#FCC30B",
    "Decent Work and Economic Growth": "#A21942",
    "Industry, Innovation, and Infrastructure": "#FD6925",
    "Reduced Inequality": "#DD1367",
    "Sustainable Cities and Communities": "#FD9D24",
    "Responsible Consumption and Production": "#BF8B2E",
    "Climate Action": "#3F7E44",
    "Life Below Water": "#0A97D9",
    "Life on Land": "#56C02B",
    "Peace, Justice, and Strong Institutions": "#00689D",
    "Partnerships for the Goals": "#19486A"
},
  fonts: {
    body: "system-ui, sans-serif",
    heading: "Georgia, serif",
    mono: "Menlo, monospace",
  },
  fontSizes: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
    "6xl": "3.75rem",
    "7xl": "4.5rem",
    "8xl": "6rem",
    "9xl": "8rem",
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  lineHeights: {
    normal: "normal",
    none: 1,
    shorter: 1.25,
    short: 1.375,
    base: 1.5,
    tall: 1.625,
    taller: "2",
    "3": ".75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "7": "1.75rem",
    "8": "2rem",
    "9": "2.25rem",
    "10": "2.5rem",
  },
  letterSpacings: {
    tighter: "-0.05em",
    tight: "-0.025em",
    normal: "0",
    wide: "0.025em",
    wider: "0.05em",
    widest: "0.1em",
  },
});

export default theme;